ALTER TABLE AGENDA DROP CONSTRAINT LABORATORIOS_AGENDA_FK;
ALTER TABLE AGENDA DROP CONSTRAINT CLIENTES_AGENDA_FK;

DROP TABLE AGENDA;
DROP TABLE LABORATORIOS;
DROP TABLE CLIENTES;

CREATE TABLE CLIENTES (
    id_cliente NUMBER NOT NULL,
    nome_cliente VARCHAR2(50) NOT NULL,
    telefone VARCHAR(30) NOT NULL,
    CONSTRAINT ID_CLIENTE_PK PRIMARY_KEY (id_cliente)
);

CREATE TABLE LABORATORIOS (
    id_lab NUMBER NOT NULL,
    qtd_maquinas NUMBER NOT NULL,
    tipo_lab VARCHAR2(30) NOT NULL,
    CONSTRAINT ID_LAB_PK PRIMARY_KEY (id_lab)
);

CREATE TABLE AGENDA (
    id_cliente NUMBER NOT NULL,
    id_lab NUMBER NOT NULL,
    id_agenda NUMBER NOT NULL,
    horaInicio TIMESTAMP NOT NULL,
    horaFim TIMESTAMP NOT NULL,
    data DATE NOT NULL,
    CONSTRAINT ID_AGENDA_PK PRIMARY_KEY (id_cliente, id_lab, id_agenda)
);

ALTER TABLE AGENDA 
ADD CONSTRAINT LABORATORIOS_AGENDA_FK
FOREIGN KEY (id_lab)
REFERENCES LABORATORIOS(id_lab)
NOT DEFERRABLE;

ALTER TABLE AGENDA
ADD CONSTRAINT CLIENTES_AGENDA_FK
FOREIGN KEY (id_cliente)
REFERENCES CLIENTES(id_cliente)
NOT DEFERRABLE;